"""create initial tables

Revision ID: 337e51274578
Revises:
Create Date: 2025-11-24 22:52:46.665182

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "337e51274578"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.VARCHAR(length=255), nullable=False),
        sa.Column("role", sa.VARCHAR(length=20), nullable=False),
        sa.Column("password", sa.VARCHAR(length=255), nullable=False),
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_by", sa.VARCHAR(length=100), nullable=False),
        sa.Column("updated_by", sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        schema="ai-powered-notes-app",
    )
    op.create_table(
        "notes",
        sa.Column("user_id", sa.CHAR(length=36), nullable=False),
        sa.Column("text", sa.TEXT(), nullable=False),
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_by", sa.VARCHAR(length=100), nullable=False),
        sa.Column("updated_by", sa.VARCHAR(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["ai-powered-notes-app.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="ai-powered-notes-app",
    )
    op.create_table(
        "multimedia",
        sa.Column("note_id", sa.CHAR(length=36), nullable=False),
        sa.Column("user_id", sa.CHAR(length=36), nullable=False),
        sa.Column("audio_url", sa.VARCHAR(length=500), nullable=True),
        sa.Column("video_url", sa.VARCHAR(length=500), nullable=True),
        sa.Column("images", sa.JSON(), nullable=True),
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_by", sa.VARCHAR(length=100), nullable=False),
        sa.Column("updated_by", sa.VARCHAR(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["ai-powered-notes-app.notes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["ai-powered-notes-app.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="ai-powered-notes-app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("multimedia", schema="ai-powered-notes-app")
    op.drop_table("notes", schema="ai-powered-notes-app")
    op.drop_table("users", schema="ai-powered-notes-app")
    # ### end Alembic commands ###
